FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY pyproject.toml README.md ./
COPY back ./back
COPY parser ./parser

RUN pip install --no-cache-dir .

CMD ["uvicorn", "back.main:app", "--host", "0.0.0.0", "--port", "8000"]
